### ISSUE TITLE
Describir en qué consiste  una Daily Scrum Meeting.

### ISSUE THREAD

**Issue by BarbaraGarciaContrera** [BarbaraGarciaContrera/Conceptos-Scrum#3]

**Comment by Gastone1547** [comment]
Este reunion se realiza diariamente con el objetivo de ver el progreso de cada uno de los integrantes,(¿que hicieron ayer?,¿que van a hacer hoy? y ¿que problemas encontraron?).su duracion es de 5min como maximo suele durar alrededor de 20min.
